# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "OCMC 2017"
email: "ocmc2017@ohio.edu"
description: "GDG DevFest is a set of events all around the world"
baseurl: "/ocmc2017"
url: "https://ocmc.scrippscollege.ohio.edu"
permalink: "/news/:title"
googleAnalyticsTrackingId: ""
googleAnalyticsSiteUrl: "ocmc.scrippscollege.ohio.edu"
googleMapsApiKey: "AIzaSyDTu56tEb0chJHWujO-XqKXceuXv_iRjZs"
siteVerification: ""

# Organizer Info
organizerName: "Ohio University"
organizerAlternateName: "Scripps Colllege of Communication and School of Communication Studies"
organizerDescription: ""
organizerEmail: "ocmc@ohio.edu"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://lviv.gdg.org.ua/"

# Head
metaKeywords: "event, ocmc, organizational communication, academic, mini conference, Scripps College of Communication, School of Communication Studies, Ohio University, Athens, research"
twitterAccount: "@OCMC2017"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "/speakers/#submit"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/news/", text: "News"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/about/", text: "About"}
 - {permalink: "/logistics/", text: "Logistics"}
bottomNavigationLinks:
 - {link: "/speakers/#submit", text: "Become a speaker"}
rightNavigationButtons:
 - {link: "/speakers/#submit", text: "Become a speaker"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Organizational Communication Mini Conference 2017"
eventDate: "October 13-15"
typeoutTextValues: '""'
typeoutFallback: ""
heroButtons:
 - {permalink: "/speakers/#submit", text: "Submit an Abstract"}
 - {permalink: "/#tickets", text: "Register for Free"}

# About Block
aboutTitle: "About OCMC"
aboutBlock:
 - {title: "Workshops", image: "workshop.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite technology!" }
 - {title: "Mini Conference", image: "conference.jpg", text: "The biggest Google related event in the country carefully crafted for you by GDG community! Awesome speakers and lots of fun!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "100", specialCharacter: "+", info: "attendees", detail: "from around the US"}
 - {count: "20",  specialCharacter: "+", info: "presenters", detail: "graduate students and accomplished scholars"}
 - {count: "36",  specialCharacter: "+", info: "hours", detail: "of communication research"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar Scholars"
rockstarSpeakersButtonText: "See all scholars"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Schoonover Center"
eventLocationLink: ""
eventStreetAddress: "20 East Union"
eventAddressLocality: "Athens"
eventAddressLocalityRegion: "Ohio"
eventPostalCode: "45701"
eventAddressCountry: "USA"
eventStartTime: "2017-10-25T10:00"
eventDoorTime: "09:00"
eventEndTime: "2017-10-25T20:00"
eventPlaceCoordinates: "39.327802, -82.1024877"
mapCenterCoordinates: "39.327802, -82.1024877"
mapMobileCenterCoordinates: "39.327802, -82.1024877"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Collaborative Classroom"
venueFeatures: ["3 huge cinema screens", "Doulby Digital Surround EX audio system", "Located directly in the city center"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "ocmc2017"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeShow: false
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Register"
ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Registration"
  price: "Free"
  priceCurrency: "USA"
  ticketsNumber: "150"
  ribbon: ""
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Register Now"
  ticketContentList: ["Acess to all of the presentations", "Lunch and dinner provided"]
  validFrom: "2017-08-25T10:00"
  validThrough: "2017-09-30T23:59"

# Footer
socialLinks:
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://www.ohio.edu/scrippscollege/", text: "Ohio University Scripps College of Communication"}
   - {link: "http://www.ohiocommstudies.com/", text: "School of Communication Studies"}
   - {link: "https://www.facebook.com/Barbara-Geralds-Institute-for-Storytelling-and-Social-Impact-110658425946804/", text: "Story Telling Institute"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:ocmc2017@ohio.edu", text: "ocmc2017@ohio.edu"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: true


# Conference Partners Block
showPartners: false

# Team Block
teamBlockTitle: "About us"
aboutUs: "Welcome to the 2017 Organizational Communication Mini-Conference (OCMC) hosted by the Scripps College of Communication and School of Communication Studies at Ohio University, Athens, Ohio.<br/><br/>The purpose of the OCMC is to feature and support graduate students pursuing research about organizational communication. The two-day event provides burgeoning scholars in the field with the opportunity to present their dissertations or other research projects, receive feedback, and socialize with their peers and with established faculty. The informal atmosphere of the OCMC is also well suited for students who wish to present and receive constructive criticism on early dissertation plans.<br/><br/>If you have any questions, please feel free to contact us <a href=\"mailto:ocmc2017@ohio.edu\">ocmc2017@ohio.edu</a>"
aboutPastConferences:
 - {title: "Northwestern University", year: "2016", link: "http://ocmc2016.soc.northwestern.edu/"}
 - {title: "Michigan State University", year: "2015", link: "http://cas.msu.edu/ocmc/#about"}
 - {title: "Purdue University", year: "2014", link: "https://ocmc2014.wordpress.com/"}
 - {title: "University of Illinois at Urbana-Champaign", year: "2013"}
 - {title: "University of Oklahoma", year: "2012"}
 - {title: "University of Missouri", year: "2011"}
 - {title: "Rutgers, The State University of New Jersey", year: "2010"}
 - {title: "Northwestern University", year: "2009"}
 - {title: "Purdue University", year: "2008"}
 - {title: "University of Illinois at Urbana-Champaign", year: "2007"}
 - {title: "Michigan State University", year: "2006"}
 - {title: "Ohio University", year: "2005"}
 - {title: "Saint Louis University", year: "2004"}
 - {title: "Western Michigan University", year: "2003"}
 - {title: "Purdue University", year: "2002"}
 - {title: "University of Illinois at Urbana-Champaign", year: "2001"}
 - {title: "Michigan State University", year: "2000"}
 - {title: "Western Michigan University", year: "1999"}
 - {title: "University of Kansas", year: "1998"}
 - {title: "Purdue University", year: "1997"}
 - {title: "University of Illinois at Urbana-Champaign", year: "1996"}
 - {title: "Michigan State University", year: "1995"}
 - {title: "University of Kansas", year: "1994"}
 - {title: "Western Michigan University", year: "1993"}
 - {title: "University of Illinois at Urbana-Champaign", year: "1992"}
 - {title: "University of Minnesota", year: "1991"}
 - {title: "Purdue University", year: "1990"}
 - {title: "Michigan State University", year: "1989"}
 - {title: "University of Illinois at Urbana-Champaign", year: "1988"}

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "40.0637378, -98.9162282"
logisticsMapMobileCenterCoordinates: "40.0637378, -98.9162282"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Athens"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Athens Public Transit is available in Athens, OH. See details on <a href="http://www.athenstransit.org/">their website or call at (740) 592-2727.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "http://www.ouinn.com/", text: "OU Inn"}
     - {link: "https://www.ihg.com/holidayinnexpress/hotels/us/en/athens/ahspd/hoteldetail", text: "Holiday In Express"}
   -
    title: "Registration"
    links:
     - {link: "http://www.ouinn.com/", text: "OU Inn"}
     - {link: "https://www.ihg.com/holidayinnexpress/hotels/us/en/athens/ahspd/hoteldetail", text: "Holiday In Express"}
   -
    title: "Attendance Details"
    links:
     - {link: "http://www.ouinn.com/", text: "OU Inn"}
     - {link: "https://www.ihg.com/holidayinnexpress/hotels/us/en/athens/ahspd/hoteldetail", text: "Holiday In Express"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: false

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didnâ€™t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
